export enum PermissionType {
  SUPERUSER = 'SUPERUSER',
  MAINTAIN = 'MAINTAIN',
  INFORM = 'INFORM',
  CREATE = 'CREATE',
  READ = 'READ',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  OTHER = 'OTHER'
}
